
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: arunvel1988/cdac-june-2025-v2
        name: guestbook-ui
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 8010
    targetPort: 8000
  selector:
    app: guestbook-ui
